// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: Proto/Gateway.proto

package ProtoGateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
}

func (x *GatewayLoginRequest) Reset() {
	*x = GatewayLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_Gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayLoginRequest) ProtoMessage() {}

func (x *GatewayLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_Gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayLoginRequest.ProtoReflect.Descriptor instead.
func (*GatewayLoginRequest) Descriptor() ([]byte, []int) {
	return file_Proto_Gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayLoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GatewayLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GatewayLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName    string `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Ips         string `protobuf:"bytes,3,opt,name=Ips,proto3" json:"Ips,omitempty"`
	GatewayName string `protobuf:"bytes,4,opt,name=GatewayName,proto3" json:"GatewayName,omitempty"`
	Status      bool   `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
}

func (x *GatewayLoginResponse) Reset() {
	*x = GatewayLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Proto_Gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayLoginResponse) ProtoMessage() {}

func (x *GatewayLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Proto_Gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayLoginResponse.ProtoReflect.Descriptor instead.
func (*GatewayLoginResponse) Descriptor() ([]byte, []int) {
	return file_Proto_Gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayLoginResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GatewayLoginResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GatewayLoginResponse) GetIps() string {
	if x != nil {
		return x.Ips
	}
	return ""
}

func (x *GatewayLoginResponse) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *GatewayLoginResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_Proto_Gateway_proto protoreflect.FileDescriptor

var file_Proto_Gateway_proto_rawDesc = []byte{
	0x0a, 0x13, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x13, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x9a, 0x01, 0x0a, 0x14, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x49, 0x70, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x47, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x47, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x32, 0x50, 0x0a, 0x0f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0c, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x14, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x62, 0x70, 0x2e, 0x67, 0x6f, 0x2f, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_Proto_Gateway_proto_rawDescOnce sync.Once
	file_Proto_Gateway_proto_rawDescData = file_Proto_Gateway_proto_rawDesc
)

func file_Proto_Gateway_proto_rawDescGZIP() []byte {
	file_Proto_Gateway_proto_rawDescOnce.Do(func() {
		file_Proto_Gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_Proto_Gateway_proto_rawDescData)
	})
	return file_Proto_Gateway_proto_rawDescData
}

var file_Proto_Gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Proto_Gateway_proto_goTypes = []interface{}{
	(*GatewayLoginRequest)(nil),  // 0: GatewayLoginRequest
	(*GatewayLoginResponse)(nil), // 1: GatewayLoginResponse
}
var file_Proto_Gateway_proto_depIdxs = []int32{
	0, // 0: GatewayServices.GatewayLogin:input_type -> GatewayLoginRequest
	1, // 1: GatewayServices.GatewayLogin:output_type -> GatewayLoginResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Proto_Gateway_proto_init() }
func file_Proto_Gateway_proto_init() {
	if File_Proto_Gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Proto_Gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Proto_Gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Proto_Gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Proto_Gateway_proto_goTypes,
		DependencyIndexes: file_Proto_Gateway_proto_depIdxs,
		MessageInfos:      file_Proto_Gateway_proto_msgTypes,
	}.Build()
	File_Proto_Gateway_proto = out.File
	file_Proto_Gateway_proto_rawDesc = nil
	file_Proto_Gateway_proto_goTypes = nil
	file_Proto_Gateway_proto_depIdxs = nil
}
