CREATE TABLE "customers" (
     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     "full_name" varchar NOT NULL,
     "user_name" varchar NOT NULL,
     "hash_password" varchar NOT NULL,
     "email" varchar NOT NULL,
     "expires_at" TIMESTAMP NOT NULL DEFAULT NOW() + INTERVAL '45 DAY',
     "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "customer_log" (
     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     "user_name" varchar NOT NULL,
     "login_at" TIMESTAMP NOT NULL DEFAULT NOW(),
     "status" bool NOT NULL DEFAULT true
);

Create table "accounts"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customer_id" bigint NOT NULL,
    "account_no" bigint NOT NULL,
    "balance" float4 NOT NULL,
    "balance_lock" float4 NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

Create table "bilans"(
   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "bilan" bigint NOT NULL,
   "balance" float4 NOT NULL,
   "is_credit" bool NOT NULL,
   "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

Create table "transactions"(
     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     "bilan_id" bigint NOT NULL,
     "account_id" bigint NOT NULL,
     "amount" float4 NOT NULL,
     "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "gateways" (
   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "user_name" varchar NOT NULL,
   "hash_password" varchar NOT NULL,
   "ips" VARCHAR NOT NULL NOT NULL,
   "gateway_name" varchar NOT NULL,
   "status" bool
);

create TABLE "config"(
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "key" varchar not null ,
    "value" varchar not null
);

CREATE UNIQUE INDEX "users_username" ON "customers" ("user_name");
CREATE UNIQUE INDEX "config_key" ON "config" ("key");
CREATE UNIQUE INDEX "ind_Accounts_acc_no" ON "accounts" ("account_no");

CREATE INDEX ON "customer_log" ("user_name", "login_at");
CREATE INDEX ON "transactions" ("bilan_id");
CREATE INDEX ON "transactions" ("account_id");

ALTER TABLE "customer_log" ADD FOREIGN KEY ("user_name") REFERENCES "customers" ("user_name");
ALTER TABLE "accounts" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("bilan_id") REFERENCES "bilans" ("id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");
