// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: Proto/Account.proto

package ProtoAccount

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountServicesClient is the client API for AccountServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServicesClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
}

type accountServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServicesClient(cc grpc.ClientConnInterface) AccountServicesClient {
	return &accountServicesClient{cc}
}

func (c *accountServicesClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/AccountServices/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServicesClient) Balance(ctx context.Context, in *BalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, "/AccountServices/Balance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServicesServer is the server API for AccountServices service.
// All implementations must embed UnimplementedAccountServicesServer
// for forward compatibility
type AccountServicesServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Balance(context.Context, *BalanceRequest) (*BalanceResponse, error)
	mustEmbedUnimplementedAccountServicesServer()
}

// UnimplementedAccountServicesServer must be embedded to have forward compatible implementations.
type UnimplementedAccountServicesServer struct {
}

func (UnimplementedAccountServicesServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAccountServicesServer) Balance(context.Context, *BalanceRequest) (*BalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Balance not implemented")
}
func (UnimplementedAccountServicesServer) mustEmbedUnimplementedAccountServicesServer() {}

// UnsafeAccountServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServicesServer will
// result in compilation errors.
type UnsafeAccountServicesServer interface {
	mustEmbedUnimplementedAccountServicesServer()
}

func RegisterAccountServicesServer(s grpc.ServiceRegistrar, srv AccountServicesServer) {
	s.RegisterService(&AccountServices_ServiceDesc, srv)
}

func _AccountServices_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServicesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountServices/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServicesServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountServices_Balance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServicesServer).Balance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AccountServices/Balance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServicesServer).Balance(ctx, req.(*BalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountServices_ServiceDesc is the grpc.ServiceDesc for AccountServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AccountServices",
	HandlerType: (*AccountServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AccountServices_Create_Handler,
		},
		{
			MethodName: "Balance",
			Handler:    _AccountServices_Balance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Proto/Account.proto",
}
